//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS06.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMVCSCEntities : DbContext
    {
        public DBMVCSCEntities()
            : base("name=DBMVCSCEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LabColaborador>().ToTable("LabCOLABORADOR");  // Mapeo de LabCOLABORADOR
            modelBuilder.Entity<USER>().ToTable("USERS");                     // Mapeo de USERS
            modelBuilder.Entity<mStatu>().ToTable("mStatus");                 // Mapeo de mStatus

            base.OnModelCreating(modelBuilder);

        }

        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<mStatu> mStatus { get; set; }
        public virtual DbSet<LabColaborador> LabColaboradors { get; set; }

    }
}
